server:
  port: 8080  # Gateway? ??

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**  # /users/** ??? user-service? ???
        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**  # /orders/** ??? order-service? ???