server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false  # API Gateway는 Eureka에 등록할 필요 없음
    fetch-registry: true   # Eureka에서 서비스 목록을 주기적으로 가져옴
    registry-fetch-interval-seconds: 5 # 5초마다 최신 서비스 목록 가져오기
  instance:
    lease-renewal-interval-in-seconds: 5 # 5초마다 상태 갱신
    lease-expiration-duration-in-seconds: 10 # 10초 동안 갱신 안 하면 서비스 제거

